---
title: "Veg Types"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Okay, So all the code crashed yesterday.  Whoo.  So now I'll write it in rmarkdown and save to local git. 

Questions:
The drought dataset, of 3 years of standarized moisture deficit greater than 1 standard deviation, shows where drought severity is high, especially when the yearly moisture deficit values are superimposed on the cores.  However, as Dan Cayan pointed out, regions can have very different ecological complexities that may influence our ability to compare droughts across regions.  Our objective now is to find a way to justify comparisions across regions.  
One way is to look at the vegetation classifications in the drought cores using either the LDAS or the Landfire classifications.  If there is a mix of vegeteation classes in each year's core, then it may not be possible to compare across regions easily.  However, if droughts seem to dominate in one or two vegetation classes, then I can say something about droughts occuring in x class duing y years and z class during w years. Or something.  
The LDAS and Landfire vegetation maps are static, built off of data from that last 20 years or so.  I'll have to find support for using this to look at droughts in early century vegetation, but Leroy mentioned that it shouldn't be a concern.  Vegetation was fairly static in the last 100 years, with the most change occuring in the last 20 years or so.
Still, I'm not entirely happen with this.  Its okay for an initial exploration, but I think we're moving to a point that this simplistic explanation is not providing anything new.  Maybe complementary.  Maybe I have to wrap my mind around how to tell this story, and i'm getting bogged down in telling someone else's story, as it were.  